name: carelog_mvp
description: "Application de gestion logistique per APF ENTREPRISE (MVP)."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase Core Services
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
  firebase_auth: ^5.1.1
  firebase_app_check: ^0.3.2+10
  cloud_functions: ^5.0.0

  # State Management & Architecture
  flutter_riverpod: ^2.5.1
  get_it: ^7.7.0
  injectable: ^2.4.2

  # Data & Serialization
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  uuid: ^4.2.1
  dio: ^5.2.1

  # Navigation & Localization
  go_router: ^14.1.0
  intl: ^0.20.2

  # Security & Storage
  flutter_secure_storage: ^4.2.1
  # PDF generation & printing
  pdf: ^3.11.3
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Code Generation
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.1
  mockito: ^5.4.0

flutter:
  generate: true
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/

  # Fonts (if needed in future)
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
