// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_rz_gegTMrh1uwdnofwTCOiJkyAcAVDA',
    appId: '1:1063794817524:web:d249d3be349bfbb5a921a1',
    messagingSenderId: '1063794817524',
    projectId: 'carelog-mv',
    authDomain: 'carelog-mv.firebaseapp.com',
    storageBucket: 'carelog-mv.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz81o8QWdn3SX9ezvvz3JlPDrbWbOBOBU',
    appId: '1:1063794817524:android:07215a15052a2410a921a1',
    messagingSenderId: '1063794817524',
    projectId: 'carelog-mv',
    storageBucket: 'carelog-mv.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_rz_gegTMrh1uwdnofwTCOiJkyAcAVDA',
    appId: '1:1063794817524:web:ad2292d585874cb1a921a1',
    messagingSenderId: '1063794817524',
    projectId: 'carelog-mv',
    authDomain: 'carelog-mv.firebaseapp.com',
    storageBucket: 'carelog-mv.firebasestorage.app',
  );
}
