name: Emulator-backed Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  emulator-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Pub
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ~/.pub-cache/hosted
          key: ubuntu-latest-pub-${{ hashFiles('**/pubspec.yaml') }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: |
          npm install -g firebase-tools --no-audit --no-fund --silent --unsafe-perm=true
          firebase --version || true

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'

      - name: Install dependencies
        run: |
          flutter pub get

      - name: Run emulator-backed integration tests
        id: run-tests
        env:
          GCLOUD_PROJECT: carelog-mv
          GOOGLE_CLOUD_PROJECT: carelog-mv
        run: |
          set -x
          echo "Runner OS: $RUNNER_OS"
          if [ -f scripts/seed_emulator.sh ]; then
            echo "Found seeder: scripts/seed_emulator.sh"
            firebase emulators:exec --only auth,firestore --project=carelog-mv "bash -lc 'bash scripts/seed_emulator.sh && flutter test integration_test/emulator_integration_test.dart'" 2>&1 | tee emulators-local.log
          elif [ -f scripts/seed_firestore.js ]; then
            echo "Found node seeder: scripts/seed_firestore.js"
            firebase emulators:exec --only auth,firestore --project=carelog-mv "bash -lc 'node scripts/seed_firestore.js && flutter test integration_test/emulator_integration_test.dart'" 2>&1 | tee emulators-local.log
          else
            echo "No seeder script found; running tests directly"
            firebase emulators:exec --only auth,firestore --project=carelog-mv "bash -lc 'flutter test integration_test/emulator_integration_test.dart'" 2>&1 | tee emulators-local.log
          fi

      - name: Upload emulator logs (always)
        uses: actions/upload-artifact@v4
        with:
          name: emulator-logs
          path: |
            emulators-local.log
            firebase-debug.log
            emulators/**/debug.log
