name: Flutter CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  analyze-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Pub
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ~/.pub-cache/hosted
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: |
          # Run flutter analyze and capture output
          output=$(flutter analyze 2>&1)
          exit_code=$?

          echo "$output"

          # Check if there are any ERROR level issues (not just info/warnings)
          if echo "$output" | grep -q "^   error - "; then
            echo "❌ Found ERROR level issues. Failing the build."
            exit 1
          elif [ $exit_code -eq 0 ]; then
            echo "✅ No linting issues found."
          else
            echo "⚠️  Found only INFO level suggestions (warnings). Allowing build to continue."
            echo "These are performance suggestions, not blocking errors."
          fi

      - name: Run tests
        run: flutter test --coverage

  build-web:
    runs-on: ubuntu-latest
    needs: analyze-test
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.base_ref == 'main')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Pub
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ~/.pub-cache/hosted
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'

      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web --web-renderer html

  build-android:
    runs-on: ubuntu-latest
    needs: analyze-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Pub
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ~/.pub-cache/hosted
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (debug)
        run: flutter build apk --debug
